language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - docker

after_success:
  - cd $TRAVIS_BUILD_DIR/assembly;
  - pwd;
  - mvn -Pdocker;
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $DOCKER_REGISTRY;
  - docker push docker.io/bcgovbrian/kapua-broker:latest;
